### PR TITLE
Code review pull request

### PR DESCRIPTION
**Pull request by avhaymart**

### CODE REVIEW

**Comment by kthomas852** [comment]
Testing - For the test requirement this member has 2 ready to go and plans to finish the remainder in the 
               near future.

Architecture - Used lots of separation in their code, great for scale-ability

Library usage - Used appropriate libraries for the project given.  Noticed that much of the the bootstrap 
                         styling was done using className references.  Given that the work was done in React an 
                         more efficient use of this library could have been accomplished by leveraging the react- 
                         bootstrap dependency and utilizing it's pre-made components.

Code quality - Code was very easy to read and naming convention followed a logical sequence.

Code cleanliness - No real loose ends left in the code and on the whole comments helped understand the flow of the code.

**Comment by avhaymart** [comment]
# Code Review for Up2 and Up2-BE

### Project Architecture
We could've had better utilization of Redux, but I understand our time limit made the project more about doing it, rather than learning new technologies. The file structure is good and labelled appropriately. Half of our project uses imported js/css files for bootstrap, and the other half uses components from react-bootstrap, which is a big issue. 

### Cloudinary
Cloudinary was probably the most memorable library used in this project. The library's implementation was very useful and created one of the coolest features for the project. However, upon usage of the Cloudinary module, lots of errors are thrown. That might be an issue with the library itself, or with our implementation of it.

### Code quality
The code quality wasn't perfect, but it wasn't bad by any means. It was a 5 day project, so we only had time to make the code work and that's it. One thing that was an issue was I was trying to fix this line of code:

     db.find({ _id: req.body.eventID }, (dbModel) => { 

db.find actually needed to be db.collection.find, but I couldn't figure out which collection the developer intended to search through. The code written could've used some comments to explain what it was doing.

### Code cleanliness
The project didn't utilise a linting tool such as eslint. Therefore, there are some areas that don't have semicolons and some that do, for example. Even without eslint, however, the code's cleanliness is in good standing.

### Testing

Testing was definitely ignored in this project; it was one of the smallest priorities we had. Although this project was a good learning experience for Enzyme, the testing requirements weren't met.

**Comment by chris12540** [comment]
```
 db.find({ _id: req.body.eventID }, (dbModel) => {
```
That was actually my code _sorry_ and I realized it too late lol 
Good find!

**Comment by kthomas852** [comment]
# Testing
More time needed for tests to be complete

# Architecture 
Used lots of separation in the code, great for scale-ability.  Redux was an interesting idea but implementation was not complete.

# Library usage
Used appropriate libraries for the project given. Noticed that much of the the bootstrap
styling was done using className references. Given that the work was done in React a
more efficient use of this library could have been accomplished by leveraging the react-
bootstrap dependency and utilizing it's pre-made components. Cloudinary was a great solution to the problem.

# Code quality
Code was very easy to read and naming convention followed a logical sequence.  There are some clever examples involving state to circumvent reference issues.

# Code cleanliness
No real loose ends left in the code and on the whole comments helped understand the flow of the code.

**Pull request merged**
